<h4 style="text-align: center;"><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: large; "><font class="Apple-style-span" color="#993300"><span class="Apple-style-span" style="font-weight: normal;"><i><span class="Apple-style-span" style="color: rgb(0, 0, 0); font-family: verdana; font-style: normal; font-size: 12px; "><img src="http://www.wow-aspect.com/lu//images/229564-School-Boy-Practicing-The-Alphabet-Poster-Art-Print.jpg" border="0" /></span></i></span></font></span></font><span class="Apple-style-span" style="font-family: arial; font-weight: normal; font-size: large; color: rgb(153, 51, 0); "><i>Практики</i></span></h4>
<div><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: small;">Вам предстоит найти ответы на вопросы о растровой графике &nbsp;и решить несколько несложных задач.</span></span></font></div>
<div><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;"><font class="Apple-style-span" color="#800000"><b><span class="Apple-tab-span" style="white-space:pre">	</span>Вопросы</b></font></span></font></div>
<div><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-weight: normal;"><span class="Apple-style-span" style="font-size: small;"><span class="Apple-style-span" style="font-family: 'trebuchet ms'; font-size: 13px; color: rgb(209, 0, 0); ">
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font color="#000000"><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;&nbsp; &nbsp; 1.&nbsp;</span></font><span><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;</span></font></span><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">как строиться изображение растровой графики?</span></font></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font color="#000000"><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;&nbsp; &nbsp; 2. дайте определение, что такое растровый графический редактор?</span></font></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font color="#000000"><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;&nbsp; &nbsp; 3. какие расширения могут иметь файлы растровой графики?</span></font></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font color="#000000"><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;&nbsp; &nbsp; 4. какие изображения можно создавать с помощью растровой графики?</span></font></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font color="#000000"><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;&nbsp; &nbsp; 5. каким образом можно получить растровое изображение?</span></font></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;"><b><font class="Apple-style-span" color="#993300">&nbsp;Задачи</font></b></span></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font class="Apple-style-span" color="#993300"><b><span class="Apple-style-span" style="color: rgb(0, 0, 0); font-weight: normal; -webkit-border-horizontal-spacing: 2px; -webkit-border-vertical-spacing: 2px; "><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;&nbsp; &nbsp; &nbsp;1. Сколько бит видеопамяти занимает информация об одном пикселе на черно-белом экране (без полутонов)?</span></font></span></b></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font class="Apple-style-span" color="#993300"><b><span class="Apple-style-span" style="color: rgb(0, 0, 0); font-weight: normal; -webkit-border-horizontal-spacing: 2px; -webkit-border-vertical-spacing: 2px; "><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&nbsp;&nbsp; &nbsp; &nbsp;2. На экране с разрешающей способностью 800х600 высвечивается 16-цветное изображение. Определить объём &nbsp; &nbsp; &nbsp; &nbsp;одной страницы видеопамяти в килобайтах.&nbsp;</span></font></span></b></font></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font class="Apple-style-span" color="#993300"><b><span class="Apple-style-span" style="color: rgb(0, 0, 0); font-weight: normal; -webkit-border-horizontal-spacing: 2px; -webkit-border-vertical-spacing: 2px; "><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">
</span></font></span></b></font></p>
<font class="Apple-style-span" color="#993300"><b><font class="Apple-style-span" face="arial">
<p class="MsoNormal" style="text-align: left;margin-top: 0cm; margin-right: 0cm; margin-left: 1cm; margin-bottom: 0.0001pt; text-indent: -1cm; line-height: normal; "><span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;"><span style="mso-list:Ignore"><span style="font:7.0pt &quot;Times New Roman&quot;"><font class="Apple-style-span" face="'Times New Roman', serif" size="4"><span class="Apple-style-span" style="font-size: 16px;">&nbsp;&nbsp; &nbsp; &nbsp;3.&nbsp;</span></font>&nbsp;</span></span></span><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">Объем видеопамяти равен 512 Кбайт, разрешающая
способность дисплея &ndash;&nbsp;800 </span></font><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;">&acute;</span></font><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;"> 600. Какое максимальное количество цветов можно использовать при
таких условиях?</span></font><o:p></o:p></p>
<p class="MsoNormal" style="text-align: left;margin-top: 0cm; margin-right: 0cm; margin-left: 1cm; margin-bottom: 0.0001pt; text-indent: -1cm; line-height: normal; "><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small;"><br /></span></font></p>
</font></b></font></span><font class="Apple-style-span" color="#993300"><b><font class="Apple-style-span" face="arial"></font></b></font></span><font class="Apple-style-span" color="#993300"><b></b></font>
<p></p>
<p style="margin-top: auto; margin-right: 0cm; margin-bottom: auto; margin-left: 18pt; "><font class="Apple-style-span" face="arial"><span class="Apple-style-span" style="font-size: small; "><b><font class="Apple-style-span" color="#993300"><br /></font></b></span></font></p>
</span></font></div>